backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
  - name: "settings"
    label: "Configuración"
    files:
      - label: "Categorías"
        name: "categories"
        file: "settings/categories.md"
        fields:
          - label: "Categoría"
            name: "category"
            widget: "object"
            fields:
              - {label: "Título ES", name: "title-es", widget: "string"}
              - {label: "Título EN", name: "title-en", widget: "string"}
              - {label: "Color", name: "color", widget: "color", default: "#FFFFFF"}
  - name: "projects"
    label: "Projects"
    folder: "content/en/projects"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
